spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/etc/config
          uri: file:/etc/config          
  
server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.99.100:3057/eureka/
  instance:
    hostname: 192.168.99.100

        